datasets:
  emotion:
    name: "dair-ai/emotion"
    max_length: 128
    vocab_size: 32000
    text_column: "text"
    label_column: "label"
    tasks:
      mlm:
        enabled: true
        mask_probability: 0.15
        max_predictions_per_seq: 20
      classification:
        enabled: true
        num_labels: 6
      contrastive:
        enabled: true
        temperature: 0.07
      pos_tag:
        enabled: true
        use_universal_tags: true
      ner:
        enabled: true
    preprocessing:
      remove_html: true
      normalize_whitespace: true
      lowercase: false
    splits:
      train: 0.8
      validation: 0.1
      test: 0.1
    
  gutenberg:
    name: "gutemberg2"
    max_length: 512
    vocab_size: 32000
    text_column: "chosen"
    summary_column: "summary"
    tasks:
      lmlm:
        enabled: true
        chunk_size: 256
        stride: 128
      ner:
        enabled: true
        use_bio_tags: true
      pos_tag:
        enabled: true
        use_universal_tags: true
      nsp:
        enabled: true
        negative_sample_rate: 0.5
      discourse:
        enabled: true
        marker_types: ["causal", "temporal", "comparison", "addition", "contrast"]
    preprocessing:
      remove_html: true
      normalize_whitespace: true
      lowercase: false
      preserve_case_for_ner: true
    splits:
      train: 0.8
      validation: 0.1
      test: 0.1

tokenizer:
  type: "sentencepiece"
  model_type: "bpe"
  vocab_size: 32000
  character_coverage: 0.9995
  max_sentence_length: 2048
  pad_to_multiple_of: 8
  special_tokens:
    pad: "[PAD]"
    unk: "[UNK]"
    cls: "[CLS]"
    sep: "[SEP]"
    mask: "[MASK]"
  training:
    input_sentence_size: 10000000
    shuffle_input_sentence: true
    train_extremely_large_corpus: true

processing:
  num_workers: 4
  batch_size: 32
  shuffle_buffer_size: 10000
  prefetch_buffer_size: "auto"
  max_samples_per_task: null
  sequence_buckets:
    enabled: true
    boundaries: [32, 64, 128, 256, 512]

output:
  return_tensors: "tf"
  output_dir: "processed_data"
  save_processed: true
  compression: "GZIP"
  monitoring:
    log_preprocessing_stats: true
    save_samples: true
    num_samples: 100

validation:
  validate_outputs: true
  max_sequence_length_quantile: 0.99
  min_sequence_length: 8
  check_label_distribution: true
  verify_special_tokens: true