transformer_tokenizer:
  type: "wordpiece"
  pretrained_model_name_or_path: "bert-base-cased"
  vocab_size: 30522
  special_tokens:
    pad: "[PAD]"
    unk: "[UNK]"
    cls: "[CLS]"
    sep: "[SEP]"
    mask: "[MASK]"

static_tokenizer:
  type: "spacy"
  model: "en_core_web_sm"
  lower_case: false
  vocab_size: 20000
  min_freq: 3
  learn_special_tokens: true
  special_tokens:
    pad: "<pad>"
    unk: "<unk>"
    cls: "<cls>"
    sep: "<sep>"
    mask: "<mask>"

label_generation:
  models:
    sentiment:
      type: "transformer"
      model: "distilbert-base-cased-finetuned-sst-2-english"
      checkpoint: "dair-ai/emotion"
    ner:
      type: "spacy"
      model: "en_core_web_lg"
      align_with_tokens: true
    pos:
      type: "spacy"
      model: "en_core_web_lg"
      align_with_tokens: true
    discourse:
      type: "transformer"
      model: "bert-base-cased"
      checkpoint: "discourse-markers-en"
      markers: ["however", "therefore", "moreover", "nevertheless", "consequently"]
    contrastive:
      type: "sklearn"
      model: "silhouette"
      clustering_method: "kmeans"
      min_clusters: 3
      max_clusters: 8
      validation_metrics: ["silhouette", "calinski_harabasz"]

datasets:
  gutenberg:
    name: "nbeerbower/gutenberg2-dpo"
    text_column: "chosen"
    label_column: null
    tasks:
      mlm:
        enabled: true
        mask_probability: 0.15
        whole_word_mask: true
        min_tokens: 1
        max_tokens: 20
      lmlm:
        enabled: true
        mask_probability: 0.15
        min_masks: 1
        max_masks: 5
        min_span: 2
        max_span: 5
      nsp:
        enabled: true
        model: "bert-base-cased"
        negative_sampling_ratio: 0.5
      ner:
        enabled: true
        model: "ner"
        batch_size: 32
      pos:
        enabled: true
        model: "pos"
        batch_size: 32
      discourse:
        enabled: true
        model: "discourse"
        markers_from_config: true
      contrastive:
        enabled: true
        validation: ["silhouette", "task_clusters"]
        tasks_for_clustering: ["ner", "pos", "discourse"]
        min_silhouette_score: 0.5
    splits:
      validation: 0.10
      test: 0.10
    max_length: 128
    preprocessing:
      remove_html: true
      normalize_unicode: true
      handle_numbers: true

  emotion:
    name: "dair-ai/emotion"
    text_column: "text"
    label_column: "label"
    tasks:
      mlm:
        enabled: true
        mask_probability: 0.15
        whole_word_mask: true
        min_tokens: 1
        max_tokens: 10
      lmlm:
        enabled: true
        mask_probability: 0.15
        min_masks: 1
        max_masks: 3
        min_span: 2
        max_span: 4
      sentiment:
        enabled: true
        model: "sentiment"
        preserve_original_labels: true
      ner:
        enabled: true
        model: "ner"
        batch_size: 32
      pos:
        enabled: true
        model: "pos"
        batch_size: 32
      discourse:
        enabled: true
        model: "discourse"
        markers_from_config: true
      contrastive:
        enabled: true
        validation: ["silhouette", "task_clusters"]
        tasks_for_clustering: ["sentiment", "ner", "pos", "discourse"]
        min_silhouette_score: 0.5
    splits:
      validation: 0.20
      test: 0.10
    max_length: 64
    preprocessing:
      remove_html: true
      normalize_unicode: true
      handle_numbers: true